### ISSUE TITLE
Can't launch/Not opening menu

### ISSUE THREAD

**Issue by vleeuwenmenno** [Nexam/NexHud#2]
Hi, I am trying out this HUD but it's not opening, the software is starting with splash screen but the keyboard shortcut is not showing any menu's.
I am not using a VR headset but it doesn't seem to work anyway.

Is this normal, do I need a VR headset for this software?

**Comment by vleeuwenmenno** [comment]
Excuse me, found it ... I had to manually set it to Classic mode to make it work.

**Comment by Nexam** [comment]
I'm glad you found the solution !
I start to dev again NexHud, hopefully i will release a new version in the next few weeks. If you have request/comment on NexHud, do not hesitate to share your opinion !
